"""Create Database

Revision ID: 3c22a5ae09e8
Revises: 
Create Date: 2024-02-16 15:03:49.975544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c22a5ae09e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('parcel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_parcel', sa.String(length=50), nullable=False),
    sa.Column('pickup_location', sa.String(length=50), nullable=True),
    sa.Column('destination', sa.String(length=50), nullable=True),
    sa.Column('latitude_pick_up_location', sa.Float(), nullable=True),
    sa.Column('longitude_pick_up_location', sa.Float(), nullable=True),
    sa.Column('latitude_destination', sa.Float(), nullable=True),
    sa.Column('longitude_destination', sa.Float(), nullable=True),
    sa.Column('image_of_parcel', sa.String(), nullable=True),
    sa.Column('receivers_name', sa.String(length=50), nullable=True),
    sa.Column('weight_of_parcel', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('present_location', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('parcel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcel_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trackers')
    op.drop_table('parcel_orders')
    op.drop_table('users')
    # ### end Alembic commands ###
