"""empty message

Revision ID: 3eb160cdcfeb
Revises: bcc07fbed937
Create Date: 2024-02-22 17:27:38.910365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb160cdcfeb'
down_revision = 'bcc07fbed937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receivers_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcel_orders', schema=None) as batch_op:
        batch_op.drop_column('receivers_phone')

    # ### end Alembic commands ###
